routes/web.php
<?php 

Auth::routes();

Route::get('/', 'PostController@index')->name('home');
Route::resource('users', 'UserController');

Route::resource('roles', 'RoleController');

Route::resource('permissions', 'PermissionController');
 
//Post Controller
// Route::resource('posts', 'PostController');
Route::delete('posts/{id}/forcedelete', 'PostController@forcedelete')->name('posts.forcedelete');
Route::get('posts/manage', 'PostController@manage')->name('posts.manage');
Route::get('posts/trashed', 'PostController@trashed')->name('posts.trashed');
Route::post('posts/{id}/restore', 'PostController@restore')->name('posts.restore');

Route::get('posts','PostController@index')->name('posts.index');
Route::post('posts','PostController@store')->name('posts.store');
Route::get('posts/create','PostController@create')->name('posts.create');
Route::get('posts/{post}','PostController@show')->name('posts.show');
Route::put('posts/{post}','PostController@update')->name('posts.update');
Route::get('posts/{post}/edit','PostController@edit')->name('posts.edit');
Route::delete('posts/{post}','PostController@destroy')->name('posts.destroy');

Route::put('posts/{post}/toggle-approve','PostController@approval')->name('posts.approval');


Route::get('/contact', function () {
    return view('contact');
});

app/Http/Controllers/PermissionController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use Auth;

//Importing laravel-permission models
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;

use Session;

class PermissionController extends Controller {

    public function __construct() {
        $this->middleware(['auth', 'isAdmin']); //isAdmin middleware lets only users with a //specific permission permission to access these resources
    }

    /**
    * Display a listing of the resource.
    *
    * @return \Illuminate\Http\Response
    */
    public function index() {
        $permissions = Permission::all(); //Get all permissions

        return view('permissions.index')->with('permissions', $permissions);
    }

    /**
    * Show the form for creating a new resource.
    *
    * @return \Illuminate\Http\Response
    */
    public function create() {
        $roles = Role::get(); //Get all roles

        return view('permissions.create')->with('roles', $roles);
    }

    /**
    * Store a newly created resource in storage.
    *
    * @param  \Illuminate\Http\Request  $request
    * @return \Illuminate\Http\Response
    */
    public function store(Request $request) {
        $this->validate($request, [
            'name'=>'required|max:40',
        ]);

        $name = $request['name'];
        $permission = new Permission();
        $permission->name = $name;

        $roles = $request['roles'];

        $permission->save();

        if (!empty($request['roles'])) { //If one or more role is selected
            foreach ($roles as $role) {
                $r = Role::where('id', '=', $role)->firstOrFail(); //Match input role to db record

                $permission = Permission::where('name', '=', $name)->first(); //Match input //permission to db record
                $r->givePermissionTo($permission);
            }
        }

        return redirect()->route('permissions.index')
            ->with('flash_message',
             'Permission'. $permission->name.' added!');

    }

    /**
    * Display the specified resource.
    *
    * @param  int  $id
    * @return \Illuminate\Http\Response
    */
    public function show($id) {
        return redirect('permissions');
    }

    /**
    * Show the form for editing the specified resource.
    *
    * @param  int  $id
    * @return \Illuminate\Http\Response
    */
    public function edit($id) {
        $permission = Permission::findOrFail($id);

        return view('permissions.edit', compact('permission'));
    }

    /**
    * Update the specified resource in storage.
    *
    * @param  \Illuminate\Http\Request  $request
    * @param  int  $id
    * @return \Illuminate\Http\Response
    */
    public function update(Request $request, $id) {
        $permission = Permission::findOrFail($id);
        $this->validate($request, [
            'name'=>'required|max:40',
        ]);
        $input = $request->all();
        $permission->fill($input)->save();

        return redirect()->route('permissions.index')
            ->with('flash_message',
             'Permission'. $permission->name.' updated!');

    }

    /**
    * Remove the specified resource from storage.
    *
    * @param  int  $id
    * @return \Illuminate\Http\Response
    */
    public function destroy($id) {
        $permission = Permission::findOrFail($id);

    //Make it impossible to delete this specific permission 
    if ($permission->name == "Administer roles & permissions") {
            return redirect()->route('permissions.index')
            ->with('flash_message',
             'Cannot delete this Permission!');
        }

        $permission->delete();

        return redirect()->route('permissions.index')
            ->with('flash_message',
             'Permission deleted!');

    }
}

resources/views/permissions/create.blade.php
@extends('layouts.app')

@section('title', '| Create Permission')

@section('content')

<div class='col-lg-4 col-lg-offset-4'>

    <h1><i class='fa fa-key'></i> Add Permission</h1>
    <br>
    <form class="form-horizontal mt-5" action="{{route('permissions.store')}}" method="post" enctype="multipart/form-data">
        {{csrf_field()}}

        <div class="form-group">
            <label for="name">Add New Parmission</label>
            <input type="text" name="name" class="form-control"><br><br>
        </div>
        
        @if(!$roles->isEmpty()) 
            <h5>If no roles exist yet</h5>
            <h6>যদি কোনও ভূমিকা এখনো বিদ্যমান থাকে</h6>
            <h3>Assign Permission to Roles</h3>

            @foreach ($roles as $role) 
                <input type="checkbox" name="roles[]" value="{{$role->id}}">{{$role->name}}<br>
            @endforeach
        @endif
        <br>
        <button class="btn btn-primary"><i class="fas fa-plus-square"></i> Add</button>
    </form>

</div>

@endsection

resources/views/permissions/edit.blade.php
@extends('layouts.app')

@section('title', '| Edit Permission')

@section('content')

<div class='col-lg-4 col-lg-offset-4'>

    <h1><i class='fa fa-key'></i> Edit {{$permission->name}}</h1>
    <br>
    <form class="form-horizontal mt-5" action="{{route('permissions.update', $permission->id)}}" method="post" enctype="multipart/form-data">
        {{method_field('PUT')}}
        {{csrf_field()}}
        {{-- Form model binding to automatically populate our fields with permission data --}}

        <div class="form-group">
            <label for="name">Permission Name</label>
            <input type="text" name="name" class="form-control" value="{{ $permission->name}}">
        </div>
        <br>
        <button class="btn btn-primary">Edit</button>
    </form>
</div>

@endsection

resources/views/permissions/index.blade.php
@extends('layouts.app')

@section('title', '| Permissions')

@section('content')

<div class="col-lg-10 col-lg-offset-1">
    <h1><i class="fa fa-key"></i>Available Permissions

    <a href="{{ route('users.index') }}" class="btn btn-default pull-right"><i class="fas fa-user-circle"></i> Users</a>
    <a href="{{ route('roles.index') }}" class="btn btn-default pull-right"><i class="fas fa-check-circle"></i> Roles</a></h1>
    <hr>
    <div class="table-responsive">
        <table class="table table-bordered table-striped">

            <thead>
                <tr>
                    <th>Permissions</th>
                    <th>Operation</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($permissions as $permission)
                <tr>
                    <td>{{ $permission->name }}</td> 
                    <td>
                        <a href="{{ URL::to('permissions/'.$permission->id.'/edit') }}" class="btn btn-info pull-left" style="margin-right: 3px;"><i class="far fa-edit"></i> Edit</a>

                        <form action="{{route('permissions.destroy', $permission->id)}}" method="post">
                            {{csrf_field()}}
                            <input type="hidden" name="_method" value="DELETE">
                            <button class="btn btn-danger"><i class="fas fa-trash-alt"></i> Delete</button>       
                        </form>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>

    <a href="{{ URL::to('permissions/create') }}" class="btn btn-success"><i class="far fa-plus-square"></i> Add Permission</a>
    

</div>

@endsection