routes/web.php
<?php 

Auth::routes();

Route::get('/', 'PostController@index')->name('home');
Route::resource('users', 'UserController');

Route::resource('roles', 'RoleController');

Route::resource('permissions', 'PermissionController');
 
//Post Controller
// Route::resource('posts', 'PostController');
Route::delete('posts/{id}/forcedelete', 'PostController@forcedelete')->name('posts.forcedelete');
Route::get('posts/manage', 'PostController@manage')->name('posts.manage');
Route::get('posts/trashed', 'PostController@trashed')->name('posts.trashed');
Route::post('posts/{id}/restore', 'PostController@restore')->name('posts.restore');

Route::get('posts','PostController@index')->name('posts.index');
Route::post('posts','PostController@store')->name('posts.store');
Route::get('posts/create','PostController@create')->name('posts.create');
Route::get('posts/{post}','PostController@show')->name('posts.show');
Route::put('posts/{post}','PostController@update')->name('posts.update');
Route::get('posts/{post}/edit','PostController@edit')->name('posts.edit');
Route::delete('posts/{post}','PostController@destroy')->name('posts.destroy');

Route::put('posts/{post}/toggle-approve','PostController@approval')->name('posts.approval');


Route::get('/contact', function () {
    return view('contact');
});

app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use Auth;
//Importing laravel-permission models
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;

use Session;

class RoleController extends Controller {

    public function __construct() {
        $this->middleware(['auth', 'isAdmin']);//isAdmin middleware lets only users with a //specific permission permission to access these resources
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index() {
        $roles = Role::all();//Get all roles

        return view('roles.index')->with('roles', $roles);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create() {
        $permissions = Permission::all();//Get all permissions

        return view('roles.create', ['permissions'=>$permissions]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request) {
    //Validate name and permissions field
        $this->validate($request, [
            'name'=>'required|unique:roles|max:10',
            'permissions' =>'required',
            ]
        );

        $name = $request['name'];
        $role = new Role();
        $role->name = $name;

        $permissions = $request['permissions'];

        $role->save();
    //Looping thru selected permissions
        foreach ($permissions as $permission) {
            $p = Permission::where('id', '=', $permission)->firstOrFail(); 
         //Fetch the newly created role and assign permission
            $role = Role::where('name', '=', $name)->first(); 
            $role->givePermissionTo($p);
        }

        return redirect()->route('roles.index')
            ->with('flash_message',
             'Role'. $role->name.' added!'); 
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id) {
        return redirect('roles');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id) {
        $role = Role::findOrFail($id);
        $permissions = Permission::all();
        // dd($permissions);
        $r_permission = $role->permissions->first();//pass Old permission role
        $r_permission ? $r_permission_id = $r_permission->id : $r_permission_id = null;

        return view('roles.edit', compact('role', 'permissions','r_permission_id'));
    }
 
    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id) {

        $role = Role::findOrFail($id);//Get role with the given id
    //Validate name and permission fields
        $this->validate($request, [
            'name'=>'required|max:10|unique:roles,name,'.$id,
            'permissions' =>'required',
        ]);

        $input = $request->except(['permissions']);
        $permissions = $request['permissions'];
        $role->fill($input)->save();

        $p_all = Permission::all();//Get all permissions

        foreach ($p_all as $p) {
            $role->revokePermissionTo($p); //Remove all permissions associated with role
        }

        foreach ($permissions as $permission) {
            $p = Permission::where('id', '=', $permission)->firstOrFail(); //Get corresponding form //permission in db
            $role->givePermissionTo($p);  //Assign permission to role
        }

        return redirect()->route('roles.index')
            ->with('flash_message',
             'Role'. $role->name.' updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $role = Role::findOrFail($id);
        $role->delete();

        return redirect()->route('roles.index')
            ->with('flash_message',
             'Role deleted!');

    }
}

resources/views/roles/create.blade.php
@extends('layouts.app')

@section('title', '| Add Role')

@section('content')

<div class='col-lg-4 col-lg-offset-4'>

    <h1><i class='fa fa-key'></i> Add Role</h1>
    <hr>
    <form class="form-horizontal mt-5" action="{{route('roles.store')}}" method="post" enctype="multipart/form-data">
        {{csrf_field()}}
        
        <div class="form-group">
            <label for="name">Name</label>
            <input type="text" name="name" class="form-control">
        </div>

        <h4><b>Assign Permissions</b></h4>

        <div class='form-group'>
            @foreach ($permissions as $permission)
                <input type="checkbox" name="permissions[]" value="{{$permission->id}}">{{$permission->name}} <br>
            @endforeach
        </div>

        <label class="col-md-4 control-label" for=""></label>
            <div class="col-md-4">
                <button class="btn btn-info btn-block"> Add </button>
            </div>
    </form>

</div>

@endsection

resources/views/roles/edit.blade.php
@extends('layouts.app')

@section('title', '| Edit Role')

@section('content')

<div class='col-lg-4 col-lg-offset-4'>
    <h1><i class='fa fa-key'></i> Edit Role: {{$role->name}}</h1>
    <hr>
    <form class="from-horizontal mt-5" action="{{route('roles.update', $role->id)}}" method="post" enctype="multipart/form-data">
        {{method_field('PUT')}}
        {{csrf_field()}}

        <div class="form-group">
            <label for="name">Role Name</label>
            <input type="text" name="name" class="form-control" value="{{$role->name}}">
        </div>

        <h5><b>Assign Permissions</b></h5>
        @foreach ($permissions as $permission)
            @if($r_permission_id == $permission->id)
                <input type="checkbox" name="permissions[]" value="{{$permission->id}}" checked="checked">{{$permission->name}} <br>
            @else
                <input type="checkbox" name="permissions[]" value="{{$permission->id}}">{{$permission->name}} <br>
            @endif
        @endforeach
        <br>
        <button class="btn btn-info btn-block"> Edit Role </button>
    </form>
    
</div>

@endsection

resources/views/roles/index.blade.php
@extends('layouts.app')

@section('title', '| Roles')

@section('content')

<div class="col-lg-10 col-lg-offset-1">
    <h1><i class="fa fa-key"></i> Roles

    <a href="{{ route('users.index') }}" class="btn btn-default pull-right">Users</a>
    <a href="{{ route('permissions.index') }}" class="btn btn-default pull-right">Permissions</a></h1>
    <hr>
    <div class="table-responsive">
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>Role</th>
                    <th>Permissions</th>
                    <th>Operation</th>
                </tr>
            </thead>

            <tbody>
                @foreach ($roles as $role)
                <tr>

                    <td>{{ $role->name }}</td>

                    <td>{{  $role->permissions()->pluck('name')->implode(' ') }}</td>{{-- Retrieve array of permissions associated to a role and convert to string --}}
                    <td>
                    <a href="{{ route('roles.edit', $role->id) }}" class="btn btn-info pull-left" style="margin-right: 3px;">Edit</a>

                    <form action="{{route('roles.destroy', $role->id)}}" method="post">
                        {{csrf_field()}}
                        <input type="hidden" name="_method" value="DELETE">
                        <button class="btn btn-danger">Delete</button>
                    </form>   

                    </td>
                </tr>
                @endforeach
            </tbody>

        </table>
    </div>

    <a href="{{ URL::to('roles/create') }}" class="btn btn-success"><i class="fas fa-plus-square"></i> Add Role</a>

</div>

@endsection